mushrooms:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASS') }}"
      port: "{{ env_var('PG_PORT') | int }}"
      dbname: mushrooms_dev
    qa:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASS') }}"
      port: "{{ env_var('PG_PORT') | int }}"
      dbname: mushrooms_qa
    prod:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASS') }}"
      port: "{{ env_var('PG_PORT') | int }}"
      dbname: mushrooms